// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMQ8VC45G03Nfnvwuc7RC6Mr1jC8a2Xw',
    appId: '1:352668972994:web:8cea646b0925e8131e885b',
    messagingSenderId: '352668972994',
    projectId: 'apppromotor-d7ea8',
    authDomain: 'apppromotor-d7ea8.firebaseapp.com',
    storageBucket: 'apppromotor-d7ea8.firebasestorage.app',
    measurementId: 'G-YZFJKYYMX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLcjHKcgsfjT356Mq9EyvuRfKmm5Ab4hw',
    appId: '1:352668972994:android:8eb1b4a0b17a54c31e885b',
    messagingSenderId: '352668972994',
    projectId: 'apppromotor-d7ea8',
    storageBucket: 'apppromotor-d7ea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpIYl8RQM9SQ8vVLrbuE1mti2ozc78Kms',
    appId: '1:352668972994:ios:d6340506dcf02cdf1e885b',
    messagingSenderId: '352668972994',
    projectId: 'apppromotor-d7ea8',
    storageBucket: 'apppromotor-d7ea8.firebasestorage.app',
    iosBundleId: 'com.example.apppromotor',
  );
}
